- hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios

  vars_files:
    - secrets.yml

  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    address_object_name: "az2_subnet"
    address_object_subnet: "20.1.3.0 255.255.255.0"
    policy_id: "4"
    policy_name: "inbound_az2"
    service_name: "ALL"
    action: "accept"
    schedule: "always"
    log_traffic: "all"

  tasks:
    - name: Apply FortiGate Configuration
      include_tasks: fortigate_config.j2
